### ISSUE TITLE
Dev Task: Balance the game

### ISSUE THREAD

**Issue by jonathaneeckhout** [jonathaneeckhout/jdungeon#66]
The game should be balanced.

I know some other projects use an excel file to calculate the values of parameters.

Example of things that should be balanced:
- Starting hp, defence, attack power of the player
- How much should these stats increase with each level?
- How much hp and attack power should each enemy have?
- How much should certain equipment enhance the stats of the player?
- ...

The game should not be easy, it should be challenging but not frustrating hard.

**Comment by NancokPS2** [comment]
Here's a simple table that i made with some assumptions.  
- Firstly i am using low numbers as to make all of them feel more impactful (what is another 1000 damage when your numbers are already unreadable in the heat of combat when they reach amounts of thousands?)    
- I am also assuming that combat will be rather active (since it is meant to be challenging) so kill times are fairly low, yet combat is meant to offer chances for players to dish out more net-damage with skill full play.   
  
| Parameters| Player | Basic enemy | Elite enemy | Boss |
|--------|--------|--------|--------|--------|
| Health | 100 | 50 | 200 | 1000 |
| Damage | 15 | 10 | 25 | 20 |
| Hits to die | 10/4/5 | 3.5 | 13 | 70 |
| Average stat shift (equip. and other modifiers) | 25% | 10% | 10% | 10% |
| Max/Rare stat shift | 50% | 70% | 20% | 20% |   
  
**Notes:**    

- Players are expected to have a way to reduce damage and restore health during combat trough their skills or some other source. This makes combat less of a an auto-battler and more of a hands-on encounter.

- Elites are strong ocassional opponents that rise above the usual enemy. They are meant to be a serious threat that requires skill to deal with, but don’t last nearly as long as an actual boss

- Bosses are more complex and are meant to be taken down trough strategy and planning, they don’t hit as hard, but their health pool means its impossible to succeed without a game-plan.
   
- Stat shift refers to how much a creature's stats can vary from their original values.  

- Stat shifts are potentially larger for weaker enemies, as to allow for them to rise to the ankles of their elite brethren from time to time. Stronger enemies retain a lower possible bonus due to the scaling nature that could mess with balance too much.
  
- Players will probably have plenty of ways to scale their power, so their gear should stay relatively tame to prevent them from potentially achieving game breaking combos. 
On average a well equipped player will be 25% better than one that has neglected their equipment, making it quite important, but the higher values are reserved for the rarer kinds of loot for the late game.  
  
**Leveling:**
- Scaling per level is usually better on the lower side to prevent differences in level from making a zone feel too hard or too easy. Thus making players have to constantly worry about leveling up (or about NOT doing so). It also means   
- The total increase of stats at max level could be around 500%-800% of the original stat values. It would be a decent middle ground. Depending on expected gameplay length.  
- Alternatively, growth could be more horizontal. Meaning that players unlock more options and features than they do stat gains. Making all enemies equally tough but providing tools that allow skilled players to achieve more.

**Comment by NancokPS2** [comment]
My biggest doubt right now is player damage, it could probably be higher.  
But all of this is with many assumptions. We'd have to decide what feel we want for the game.

**Comment by jonathaneeckhout** [comment]
Great initial proposal for stats.

I do think that we should go for a level cap of 100.

How do we translate these number you propose to the current equipment we currently have?

How much defense should each piece have?

We have a leather set, mail set and plate set.

We have 4 different pieces per armor set: Head, Body, Legs, Arms  

I'd say we should aim to allow players to use the leather set at +- level 10, mail at +- level 20 and plate at +- level 30.
I think we should spread the level required to wield a piece should be spread a bit over some levels around the aimed level per set

For weapons we currently have 3 weapons, club, sword, axe.

How much attack power should each weapon have? What should be the attack speed?

We also have 2 rings to add some stats like max hp, defense, ...

Once we have these numbers we can add them in the game and test them.

**Comment by NancokPS2** [comment]
Defense from armor, depending on combat speed, may have to be in the 1-4 range per tier.  
In games like Starcraft all armor increases are by 1 at a time, except for bigger units which are given more defense (usually a +2) to be tankier against swarms of units dealing plinking amounts of damage. And these increases are split into 3 tiers.  
    
However, it also depends on how we want armor to work. Do we want armor to just be simple tiers of increasingly better benefits? do we want armor that's better for certain situations like elemental based resistances? Should tankier armor make you slower in combat or do we let class restrictions sort that out?    
  
At the end of the day, it all boils down to the play-style. A character that has to stand and soak up damage NEEDS good defense to be viable. A character that has good mobility can forgo armor in exchange of more offensive boosts, and sometimes may need to be barred from good armor to keep the balance.     
  
Here's some ideas:  
  
- Trade-offs: different kinds of armor grant different kinds of boosts, some give more damage and less defense, some increase mana capacity and even lower max health. Some armors may have a bit of everything, but give a standard and comparatively unimpressive boost. Players are encouraged to optimize their builds forgoing the stats they don't need. But those that prefer a more generalist approach still have the standard versions.  

- Power-up armor: armor is merely a straight and necessary upgrade, they all grant good boosts and its main purpose is to give players an edge at the cost of having to pay or grind for the gear. The decision lays on which boosts maximize a player's build (a.k.a number crunching). Many classic MMOs work like this. 

- Dedicated boost per slot: each equipment slot can only boost a specific kind of stat, the main armor can only boost defense while rings may only other stats or give a secondary effect (like increased mana/health regeneration). 
Boots could be dedicated to mobility boosts, gloves to attack buffs, etc.
The best way to balance this approach is to make some armor class locked, meaning that a class that is already good at damage cannot also have the same defensive boosts as a tankier class and a tankier class cannot have the same access to the boosts of a glass cannon. This approach facilitates balance but is fairly restrictive.
  
------------------------------

Attack speed would largely dictate the difficulty of the game. I was thinking that an average of 1 attack per 0.5s is pretty fast but not too fast for MMO controls. Otherwise a middle ground of 1/0.7s could work better.   
This is just a standard, but i did make the stats table based on the assumption that all damage values are over the same span of time (so elites do 25 over 0.5s and players deal 15 over 0.5s)  
    
-----------------------------
  
Weapons, if we want to avoid the usual tiering of starting with a stick, ending with a buster sword. They could have typings beyond just their range. Each type would have a defining difference over weapons from another type, regardless of tier.  
  
Some examples:  
  
- Swords: base-line melee weapon. Good damage plus a small defensive boost for the melee inclined.  
- Clubs/Maces: higher damage, slower time to hit. Making them hard to use with an evasive character but worth it if the character can tank hits.    
- Dagger: fast close range attacks, maybe with residual, non-stacking damage. Good for characters that don't rely on their auto attack all that much or simply cannot afford to stay up-close for long.

- Bow: standard fast firing ranged weapon.
- Crossbow: slow firing with big hits. Usable as a battle starter or with skills that support its repeated, yet slow use.  
- Javelin/throwables: shorter ranged with high damage and a considerably long delay between attacks, but near instant start up. Worth it for characters that spend most of their time using abilities rather than attacking.  
 
- Orb: support weapon that restores some mana with each attack. But has pitiful damage. 
- Staff: weapon that provides some defense and has considerably good range for being melee.
- Wand: auto attacks when spending mana. For big spenders.
